# Generated by Django 4.0.1 on 2022-02-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100)),
                ('m_roll', models.IntegerField()),
                ('m_number', models.IntegerField()),
                ('m_year', models.IntegerField()),
            ],
        ),
    ]
